import { join } from 'path'
import { parseTypeDocJSON } from './parser'
import type { TypeDocRoot, DocSection } from './types'
import { logger } from '@/lib/utils/logger'

/**
 * Loads and parses TypeDoc-generated API documentation from JSON file.
 *
 * @returns Array of documentation sections organized by category
 *
 * @remarks
 * This function:
 * 1. Reads the TypeDoc-generated JSON file from `public/docs/api.json`
 * 2. Parses the raw TypeDoc data into structured documentation sections
 * 3. Returns an empty array if the file is missing or invalid
 *
 * The TypeDoc JSON file should be generated by running:
 * ```bash
 * typedoc --options typedoc.json
 * ```
 *
 * @example
 * ```ts
 * import { loadDocumentation } from '@/lib/docs/loader'
 *
 * // In a server component
 * export default async function DocsPage() {
 *   const sections = await loadDocumentation()
 *   return <DocsList sections={sections} />
 * }
 * ```
 *
 * @throws Does not throw - errors are logged and an empty array is returned
 *
 * @category Documentation
 * @public
 */
export async function loadDocumentation(): Promise<DocSection[]> {
  try {
    const filePath = join(process.cwd(), 'public/docs/api.json')
    const typeDocData = (await Bun.file(filePath).json()) as TypeDocRoot
    return parseTypeDocJSON(typeDocData)
  } catch (error) {
    logger.error('Failed to load TypeDoc JSON', 'TypeDoc', error)
    return []
  }
}
